sudo: true
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
language: erlang
otp_release:
  - 22.2
  - 21.3
 script:
  - ./rebar3 steamroll --check
  - ./rebar3 compile
  - ./rebar3 eunit
  - ./rebar3 cover
  - ./rebar3 as test coveralls send
# - ./rebar3 dialyzer
  - ./rebar3 as test geas
